### PR TITLE
GRDB: use `timeIntervalSince1970` for read queries

### LINKED ISSUE #3235: Auto-archive after 24 hours not working with GRDB
### Description

When auto-archive for played episodes is set to "after 24 hours", and GRDB flag is enabled, played episodes are deleted before the 24-hour window is complete.

I suspect that the issue relates to the following:
> GRDB 2+ interprets numerical values as timestamps that fuel Date(timeIntervalSince1970:)

but in the query we pass a Swift Date object without calling `timeIntervalSince1970`

https://github.com/Automattic/pocket-casts-ios/blob/c0509890cf52acd145bfe688d1473801c2cbbb89/podcasts/ArchiveHelper.swift#L36-L43

cc: @leandroalonso 

### Step-by-step reproduction instructions

1. Enable GRDB feature flag
2. Set "Auto Archive Played Episodes" setting to "After 24 hours"
3. Play episode to completion.
4. Note that episode is not deleted automatically
5. Perform a pull to refresh to initiate a sync (or wait for the next sync event)
6. Notice that the played episode is archived, before 24 hours has passed
7. Repeating the test with GRDB feature flag disabled does not yield the same result

### Screenshots or screen recording

_No response_

### Did you search for existing bug reports?

- [x] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

iPhone 14 Pro, PocketCasts 7.90.0.3, iOS 18.5

### PR DESCRIPTION
**Pull request by leandroalonso**
Fixes #3235

We have updated GRDB `executeUpdate` to ensure using `timeIntervalSince1970`. However, `executeQuery` was missing. Which would cause issues with any queries using `Date`. 

## To test

I recommend reproducing the issue on `develop` so you can understand what was going on.

1. Ensure GRDB feature flag is enabled
2. Go to Profile > Settings > Auto Archive > set  "Played Episodes" to "After 24 hours"
3. Play episode to completion.
4. Note that episode is not deleted automatically
5. Perform a pull to refresh to initiate a sync (or wait for the next sync event)
6. ✅  Notice that the played episode is **NOT** archived, before 24 hours has passed

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: Modules/DataModel/Sources/PocketCastsDataModel/Private/DB/GRDB/GRDBDatabase.swift [hunk 1]
```diff
@@ -17,9 +17,14 @@ class GRDBDatabase: PCDatabase {
...
     func executeQuery(_ sql: String, values: [Any]?) throws -> any PCDBResultSet {
+        // We want GRDB to query `Date` the same way FMDB does: using `timeIntervalSince1970`
+        // In terms of raw performance changing that on the model layer would be much better.
+        // However, that's a large change that we want to avoid.
+        let filteredValues = values?.map { ($0 as? Date)?.timeIntervalSince1970 ?? $0 }
+
         // Invalid arguments will result in a crash in the application
         // TODO: when releasing GRDB discuss if we want to make this optional
-        let rowCursor = try Row.fetchCursor(database, sql: sql, arguments: StatementArguments(values != nil ? values! : [])!)
+        let rowCursor = try Row.fetchCursor(database, sql: sql, arguments: StatementArguments(values != nil ? filteredValues! : [])!)
```
Comment (danielebogo) [inline Modules/DataModel/Sources/PocketCastsDataModel/Private/DB/GRDB/GRDBDatabase.swift]: Should this be `filteredValues != nil ? filteredValues! : [:]`?

**Review by danielebogo — APPROVED** [review]
@leandroalonso it's working as described!
I left just one comment. Let me know if that makes sense.

File: Modules/DataModel/Sources/PocketCastsDataModel/Private/DB/GRDB/GRDBDatabase.swift (hunk 1 above)
Comment (leandroalonso) [reply Modules/DataModel/Sources/PocketCastsDataModel/Private/DB/GRDB/GRDBDatabase.swift]: Ops, yes! Changed in 484b14a31e9e7e6e4f96b9fe2be7b2915b84d130
