### PR TITLE
Fix #2165: Exclude link from AirDrop export

### LINKED ISSUE #2165: Sharing with AirDrop fails
## Steps

* Create a clip or image using the Sharing feature
* Attempt to AirDrop
* The process fails

### PR DESCRIPTION
**Pull request by bjtitus**
| 📘 Part of: #1910 |
|:---:|

Fixes #2165

AirDrop exporting doesn't support multiple items so we need to exclude these items from AirDrop shares

## To test

* Play an episode
* Tap "Share"
* Tap "Episode"
* Tap "More"
* Try AirDrop using a local computer or other device
* Ensure that the image file is shared
* Go back to the Now Playing screen
* Tap "Share"
* Tap "Clip" & create a clip
* Tap "More"
* Try AirDrop using a local computer or other device
* Ensure that a video file is shared

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/59">7.73</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: podcasts/Sharing/ActivityItemSourceItem.swift [hunk 1]
```diff
@@ -0,0 +1,20 @@
+class ActivityItemSourceItem: NSObject, UIActivityItemSource {
+    let item: Any
+    let disallowedActivityTypes: [UIActivity.ActivityType]?
```
Comment (danielebogo) [inline podcasts/Sharing/ActivityItemSourceItem.swift:3]: Nit: could this be a Set instead? If we don't care about the order, it could be better when checking the content

**Review by danielebogo — APPROVED** [review]
Tested as described and it worked!
I left just one nit but not a blocker! :shipit:
