### PR TITLE
Fixed layout on Edit Folder screen (#53)

### LINKED ISSUE #53: Edit folder screen has too many horizontal dividers
It looks to me like the Edit Folder screen has a lot of dividers. I think at least one of these could be removed (I'm looking at the two dividers between the colors and the delete button in particular), but I'm curious what @adamzelinski thinks.

Screen Shot 2022-07-13 at 12 24 54 PM

### PR DESCRIPTION
**Pull request by rviljoen**
Fixes #53

Fixed the layout of the Edit Folder screen based on design feedback.

## To test

Edit an existing folder and compare the layout with the designs attached to issue 

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

File: podcasts/EditFolderView.swift [hunk 1]
```diff
@@ -87,3 +91,16 @@ struct EditFolderView: View {
...
+        Group {
+            ForEach (["iPhone 14 Pro", "iPhone 14 Pro Max", "iPhone 13 mini"], id: \.self) { simulator in
+                EditFolderView(model: FolderModel(), dismissAction: { _ in })
+                    .environmentObject(Theme(previewTheme: .light))
+                    .previewDevice(PreviewDevice(rawValue: simulator))
+                    .previewDisplayName(simulator)
+            }
+        }
+    }
+}
```
Comment (leandroalonso) [inline podcasts/EditFolderView.swift]: We already have a modifier to allow testing in different devices:

```suggestion
struct EditFolderView_Previews: PreviewProvider {
    static var previews: some View {
        EditFolderView(model: FolderModel(), dismissAction: { _ in })
            .environmentObject(Theme(previewTheme: .light))
            .previewOnAllDevices()
    }
}
```

**Review by leandroalonso — CHANGES_REQUESTED** [review]
Tested and it workes as described.

Left just one comment about using our own preview modifier. :)

File: podcasts/EditFolderView.swift (hunk 1 above)
Comment (rviljoen) [reply podcasts/EditFolderView.swift]: @leandroalonso Thanks so much for pointing that out. I have committed your suggestion.

**Review by leandroalonso — APPROVED** [review]
