### PR TITLE
Fixes bar for episode selection in Podcast screen

### LINKED ISSUE #1302: Nav bar issues on iPhone 13 Mini
### Description

A user on [Twitter/X](https://twitter.com/trevorheins/status/1735362832038785248) reported the navbar looking wonky on iPhone 13 Mini. 

### Step-by-step reproduction instructions

I wasn't able to replicate this on my end, but below is a screenshot from the user. 

### Screenshots or screen recording

GBU_TDaW0AAB-lk

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

iPhone 13 Mini. 
I asked for the app and iOS version.

### PR DESCRIPTION
**Pull request by bjtitus**
On smaller devices, this navbar was cut off because we had incorrect sizing for various screen sizes. I refactored this to use the `safeAreaInset` and also to refresh the constraint when the safe area inset changes.

This also increases the height just a bit because it doesn't cover the full bar on dynamic island devices.

Fixes #1302

| Before | After |
| -- | -- |
|  |  |

| Before | After |
| -- | -- |
|  |  |

## To test

* Build and run for iPhone 13 Mini simulator
* Navigate to Podcast screen
* Tap and hold to begin cell selection
* Ensure that top bar controls are visible and functional

Repeat steps on several different devices including iPhone 15 Pro and Pro Max, iPhone 8, and iPad

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/50">7.65</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: podcasts/PodcastViewController.swift [hunk 1]
```diff
@@ -165,21 +165,8 @@ class PodcastViewController: FakeNavViewController, PodcastActionsDelegate, Sync
...
-        case 320...380, 760...1024:
-            setConstant = 65.0
-        /* Covers most modern devices (380+ width),
-         from iPhone 6 Plus (414) to iPhone 14 Pro Max (430) */
-        default:
-            setConstant = 90.0
-        }
-
-        self.multiSelectHeaderViewConstraint.constant = setConstant
+        let heightConstant = 40 + view.safeAreaInsets.top
```
Comment (leandroalonso) [inline podcasts/PodcastViewController.swift]: What is this `40`? Maybe add it to a var so we know what it means?

**Review by leandroalonso — APPROVED** [review]
@bjtitus for the iPhone mini, 8 and iPad (without dynamic island) I can see a bit of the bar below:

| iPhone 8 | iPad |
| --------- | ---- |
| Simulator Screenshot - iPhone 8 - 2024-05-24 at 13 28 46 | Simulator Screenshot - iPad mini (6th generation) - 2024-05-24 at 13 31 57 |

Not a big deal and not a blocker, sharing just in case.

File: podcasts/PodcastViewController.swift (hunk 1 above)
Comment (bjtitus) [reply podcasts/PodcastViewController.swift]: I'll just rearrange this so the safeAreaInset is applied in the line below. It's just the height constant.
