### PR TITLE
Dismiss search if already active when double tap is performed on tab bar

### LINKED ISSUE #1652: Search: tapping Discover/Podcasts with the search open should dismiss it
### Description

When tapping Podcast or Discover tab bar item with the search open, the keyboard is shown again for a new search instead of dismissing the search.

### Step-by-step reproduction instructions

1. Tap Discover or Podcasts at the tab bar
2. Tap it again so the search starts
3. Dismiss the keyboard or search for something
4. Tap the tab bar item again
5. Search restart and the keyboard is shown again instead of dismissing search

### Screenshots or screen recording

_No response_

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

_No response_

### PR DESCRIPTION
**Pull request by rviljoen**
Fixes #1652 

Search: tapping Discover/Podcasts with the search open should dismiss it

## To test

1. Tap Discover or Podcasts on the tab bar
2. Tap it again so the search starts
3. Dismiss the keyboard or search for something
4. Tap the tab bar item again
5. Search should be dismissed at this point. Old behaviour was for search to restart and the keyboard to be shown again, which should not happen

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

File: podcasts/DiscoverViewController.swift [hunk 1]
```diff
@@ -95,7 +95,13 @@ class DiscoverViewController: PCViewController {
         if mainScrollView.contentOffset.y.rounded(.down) > defaultOffset.rounded(.down) {
             mainScrollView.setContentOffset(CGPoint(x: 0, y: defaultOffset), animated: true)
         } else {
-            searchController.searchTextField.becomeFirstResponder()
+            // When double-tapping on tab bar, dismiss the search if already active
+            // else give focus to the search field
+            if searchController.cancelButtonShowing {
+                searchController.cancelTapped(self)
```
Comment (rviljoen) [inline podcasts/DiscoverViewController.swift:101]: - Feels a bit hacky to simulate a button tap, but not sure if it is work duplicating the code in that method or refactoring it.
- Also, should I pass `self` or `nil` or not important? More of a style question I guess.

**Comment by rviljoen** [comment]
@leandroalonso Since you logged this issue, I would appreciate your eyes on the proposed fix. Also see my comment on the change for some guidance, please.

File: podcasts/DiscoverViewController.swift (hunk 1 above)
Comment (leandroalonso) [reply podcasts/DiscoverViewController.swift:101]: I think it's fine to pass `self`.

While it seems hack I think it's a ok trade-off for a gesture I assume not many people use that much. I learned of that quite recently by the way.

**Review by leandroalonso — APPROVED** [review]

**Comment by leandroalonso** [comment]
@rviljoen all good on my testing, I think your solution is ready to go. :)
