### PR TITLE
Adjust ExtraDark theme's background color for Choose Podcasts/Create …

### LINKED ISSUE #886: Extra Dark Theme: Possible issues with folder screens
### Actual behavior

When you are adding podcasts to a folder or use the 'add/edit folder' button, the colors don't seem to match the extra dark theme

image image

### Steps to reproduce the behavior

- Try adding/editing podcasts for a folder and notice the folders shown. 
- Alternatively, try creating a new folder

### PR DESCRIPTION
**Pull request by mrpolanco**
Fixes https://github.com/Automattic/pocket-casts-ios/issues/886#issuecomment-1574798168

The current color scheme for the Extra Dark theme is consistent with the design palette: 

https://podcast.emily.tools/themes/?pc_validation

The spacing for the Search bar in the Choose Podcasts view was adjusted, as [reported in the issue](https://github.com/Automattic/pocket-casts-ios/issues/886#issuecomment-1574798168):

spacing-side

## To test

Open a folder and tap on the ellipsis on the top right. From the menu, tap Add or Remove Podcasts. There is now spacing between the Search box and the navigation title.

## Checklist

- [✅] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [✅] I have considered adding unit tests for my changes.
- [✅] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

File: podcasts/ThemeColor.swift [hunk 1]
```diff
@@ -4,7 +4,7 @@ import PocketCastsUtils
 struct ThemeColor {
     private static let primaryUi01Light = UIColor(hex: "#FFFFFF")
     private static let primaryUi01Dark = UIColor(hex: "#292B2E")
-    private static let primaryUi01ExtraDark = UIColor(hex: "#222427")
+    private static let primaryUi01ExtraDark = UIColor(hex: "#000000")
```
Comment (leandroalonso) [inline podcasts/ThemeColor.swift]: We can't edit this file, as stated by this line it is auto-generated: https://github.com/Automattic/pocket-casts-ios/blob/trunk/podcasts/ThemeColor.swift#L3

What we can do is tweak the places that use those colors. You can compare all available colors here: https://podcast.emily.tools/themes/?pc_validation

**Review by leandroalonso — CHANGES_REQUESTED** [review]

File: podcasts/ThemeColor.swift (hunk 1 above)
Comment (mrpolanco) [reply podcasts/ThemeColor.swift]: Thank you for the colors link @leandroalonso! Very useful to have.

I have reverted the ThemeColor file changes with my latest commit.

Comment (mrpolanco) [reply podcasts/ThemeColor.swift]: @leandroalonso Looking at the [theme colors](https://podcast.emily.tools/themes/?pc_validation) link, it seems that the ExtraDark theme is displaying as expected.

It may be worth revisiting the color palette for the Extra Dark theme, as it seems to be a slightly darker palette than the Default Dark theme. The Theme selection previews for Extra Dark depict a monochrome palette without any accent colors (i.e., icons as #50D0F1). 

For now, I'll submit this PR with only the Search bar padding for the Choose Podcasts screen and leave the palette for the Extra Dark theme untouched.

SearchBarPadding-side

**Review by mrpolanco — COMMENTED** [review]
Changes to ThemeColor file reverted.

**Comment by leandroalonso** [comment]
@mrpolanco can you update the PR description? I believe that with the `ThemeColor` reversion only the margin is being addressed in this PR, right?

**Comment by mrpolanco** [comment]
> @mrpolanco can you update the PR description? I believe that with the `ThemeColor` reversion only the margin is being addressed in this PR, right?

[PR description](https://github.com/Automattic/pocket-casts-ios/pull/912#issue-1761603650) updated to reference Search bar margin update.

**Review by leandroalonso — CHANGES_REQUESTED** [review]
@mrpolanco

The changes fixes the margin for when selecting podcasts from inside a folder but it creates another issue when creating a folder (Podcasts > top left Folder icon) — in which the margin is now big:

| Creating new folder | Selecting existing podcasts |
| -------------------- | --------------------------- |
| Simulator Screen Shot - iPhone 14 - 2023-06-27 at 15 17 16 | Simulator Screen Shot - iPhone 14 - 2023-06-27 at 15 20 50 |

**Comment by mrpolanco** [comment]
@leandroalonso Thanks for spotting this! I've reviewed the views that use the `PodcastPickerView` (`EditFolderPodcastsView` and `CreateFolderView`) and can confirm that the top margin for the Search bar is now consistent for the "Choose Podcasts" and "Create Folder" screens.

**Current spacing issue**:

Current-Search-Bar-Padding-iOS14Pro

***

**Previous commit (`d60d349`)**:

Previous-Commit-Search-Bar-Padding-iOS14Pro

***

**Latest commit (`6b2acec`)**:

*iPhone 14 Pro - 460 ppi*:

Search-Bar-Padding-iOS14Pro

*SE 2nd Gen - 326 ppi*:

Search-Bar-Padding-SE-2ndGen

*iPad Pro 12.9 - 264 ppi*: 

Create Folder:

Create-Folder-Search-Bar-Padding-iPadPro-6Gen

Choose Podcasts:

Choose-Podcasts-Search-Bar-Padding-iPadPro-6Gen

**Review by leandroalonso — APPROVED** [review]
@mrpolanco thanks for fixing this! I went ahead and added your fix to `CHANGELOG.md` so we can merge the pr.
