### PR TITLE
Transcripts: Reset scroll position when changing transcript episode

### LINKED ISSUE #2092: Transcripts: transcript position is not reset when changing episode
Steps to reproduce:

- Open the app
- Start playing an episode with a transcript
- Add to the UpNext queue another episode with a transcript
- Open the full screen player
- Open the transcript view
- Scroll down
- Close transcript view
- Wait for episode to finish and the next one start
- Open transcript view
- See that the transcript is on previous position instead of the start of the transcript

### PR DESCRIPTION
**Pull request by SergioEstevao**
| 📘 Part of: #1848  |  
|:---:|

Fixes #2092 

This PR ensures that a new transcript is loaded we reset the transcript position to the beginning. 

## To test

 - Start the app
 - Ensure that you have `transcripts` and `newShowNotesEndpoint` FF enabled
 - Play an episode that as transcripts support. EX: "Cautionary Tales"
 - Add another episode with transcripts to be played in your UpNext Queue
 - Open the full screen player
 - Tap on transcripts option
 - Scroll around in the transcripts to the end of it
 - Await for the episode to get to the end and the new episode starts
 - Check that position is reset to the start.

## Checklist

- [ ] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/57">7.71 ❄️</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: podcasts/TranscriptViewController.swift [hunk 1]
```diff
@@ -292,19 +292,25 @@ class TranscriptViewController: PlayerItemViewController {
         activityIndicatorView.stopAnimating()
     }
 
+    private var previousEpisodeUUID: String?
```
Comment (leandroalonso) [inline podcasts/TranscriptViewController.swift]: I don't think we need to add this logic to `TranscriptViewController`, we can just reset position on the `update` method, which gets called only when `playbackTrackChanged` is fired

**Comment by leandroalonso** [comment]
~I submitted a simple version in #2094~

Never mind, my solution doesn't work for one user case: loading the transcript for the first time — which is the originallyr reported bug.

**Review by leandroalonso — APPROVED** [review]
