### PR TITLE
Fix/1644 show dynamic island on player

### LINKED ISSUE #1644: Dynamic Island suppressed when viewing full player main view
From a review:

> When the Player window (with Now Plsying, Details, etc) is open, whatever is being displayed in the Dynamic Island is suppressed unless you tap on it or switch between tabs (e.g. from Now Playing to Details) (in which case that display is temporarily enabled. (The Dynamic Island display is also re-enabled if you open the Playback Effects dialog.) (I tried the support email, but it seems that is provided only for premium users.)

To reproduce:

1. Do anything on your phone that will enable something on the Dynamic Island
2. Open Pocket Casts
3. Open the full player
4. Check how the Dynamic Island will be suppressed

### PR DESCRIPTION
**Pull request by SergioEstevao**
| 📘 Part of: #1644 |  
|:---:|

Fixes #1644 #2203  

This PR fixes the two issues above regarding the dynamic island:
- Increases the spacing from the top tab bar in the player and the dynamic island
- Keep the dynamic island visible ( and also the Home Indicator)

## To test

1. Start the app on a device that support the dynamic island ( iPhone 12 and above)
2. Switch to the clock app and start a timer
3. Go back to the app
4. Play an episode
5. Open the full screen player
6. Check that the dynamic island and the timer on the island stays visible
7. Check that the spacing to the tab component on top of the full player is good.

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/61">7.75 ❄️</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: podcasts/PlayerContainerViewController.swift [hunk 1]
```diff
@@ -248,7 +248,7 @@ class PlayerContainerViewController: SimpleNotificationsViewController, PlayerTa
     private func adjustHeaderConstraintIfNeeded() {
         guard let window = view.window else { return }
 
-        let requiredHeight = 45 + UIUtil.statusBarHeight(in: window)
+        let requiredHeight = 50 + UIUtil.statusBarHeight(in: window)
```
Comment (SergioEstevao) [inline podcasts/PlayerContainerViewController.swift:251]: I tried to used the SafeArea object instead of this, but there was complications with the full screen player animations so I opted for this simpler approach.

**Comment by danielebogo** [comment]
@sergio can you update the CHANGELOG as it addresses 2 issues?

**Review by danielebogo — APPROVED** [review]
All good! It works!

Let's just update the CHANGELOG for this

**Comment by SergioEstevao** [comment]
Changelog updated here: https://github.com/Automattic/pocket-casts-ios/pull/2304/commits/0351eecc500804b721d07c9e08b2d91a02be883b

**Comment by danielebogo** [comment]
Thanks @SergioEstevao ! :shipit:
