### PR TITLE
Folders: Select all action is missing fix

### LINKED ISSUE #143: Folders: Select all action is missing
### Description
Currently, the 'select all' action for folders is not being displayed within the create folder modal.

[**Designs**](https://www.figma.com/file/hxXdVc0icUYyz2fWHT7roh/Pocket-Casts-Folders?node-id=283%3A26776)

Screen Shot 2022-08-05 at 1 09 36 pm

### PR DESCRIPTION
**Pull request by fsalata**
Fixes #143

## To test
- Create a new folder
- It should show the select/deselect all button

## Video
https://user-images.githubusercontent.com/7861088/197297636-1303a775-a0cb-4c58-8777-7b151d20eaab.mp4

## Checklist

- [X] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [X] I have considered adding unit tests for my changes.
- [X] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

File: podcasts/CreateFolderView.swift [hunk 1]
```diff
@@ -64,6 +64,14 @@ struct CreateFolderView: View {
                         }
                         .accessibilityLabel(L10n.close)
                     }
+                    ToolbarItem(placement: .navigationBarTrailing) {
+                        Button {
+                            pickerModel.toggleSelectAll()
+                        } label: {
+                            Text(pickerModel.hasSelectedAll ? L10n.deselectAll : L10n.selectAll)
+                        }
+                        .foregroundColor(ThemeColor.secondaryIcon01(for: theme.activeTheme).color)
```
Comment (leandroalonso) [inline podcasts/CreateFolderView.swift:73]: Not related to this PR but just leaving it here for future reference: I believe how we can refer to theme colors can be better.

The way we do now we:

1. Refer to another static class `ThemeColor`
2. Pass the active theme as an argument
3. Make the conversion to `Color`

It would be better if we could just do `theme.secondaryIcon01` or something like that.

**Review by leandroalonso — APPROVED** [review]
