### PR TITLE
Signing back in: fixes issues with outdated podcast information

### LINKED ISSUE #791: Podcasts being removed from folders
Internal discussions: p1679634149115029-slack-C02A333D8LQ

### Expected behavior

Podcasts added to the folders are not removed without the user taking any action.

### Actual behavior

Podcasts were removed from folders. Two reports from users and one from @joashrajin. Some of them noticed the issue after updating the app.

User reports:
* 6063249-zd-woothemes
* 6071012-zd-woothemes

##### Both issues were reported from Pocket Casts 7.34

### PR DESCRIPTION
**Pull request by leandroalonso**
Fixes https://github.com/Automattic/pocket-casts-ios/issues/791#issuecomment-2125086525

We recently had an issue where a user had all their podcasts removed from folders when signing back in on another device.

This happened because they had outdated information and the app marked it as unsynced.

### With `onlyMarkPodcastsUnsyncedForNewUsers` enabled

1. Go to Profile > Settings > Beta Features > enable `onlyMarkPodcastsUnsyncedForNewUsers`
1. Sign in to a Plus account
2. Create a folder with some podcasts in it and refresh
3. Log out
4. Go to Settings > Developer > Clear all folder information
5. Subscribe to a few new podcasts
6. Log back into the same account
7. ✅ Under "Podcasts" the folder should be visible and with the same podcasts from before
8. Go to Profile > Refresh Now
9. ✅  Login into the web player, and ensure the newly subscribed podcasts were correctly synced

### With `onlyMarkPodcastsUnsyncedForNewUsers` disabled

1. Go to Profile > Settings > Beta Features > disable `onlyMarkPodcastsUnsyncedForNewUsers`
1. Add a breakpoint in `SyncSigninViewController.swift:337`
1. Sign in to a Plus account
2. Create a folder with some podcasts in it and refresh
3. Log out
4. Go to Settings > Developer > Clear all folder information
6. Log back into the same account
7. ✅ Breakpoint should hit
8. ✅ Under "Podcasts" the podcasts will be out of their folders

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/50">7.65</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: podcasts/AuthenticationHelper.swift [hunk 1]
```diff
@@ -65,7 +65,9 @@ class AuthenticationHelper {
         ServerSettings.refreshToken = response.refreshToken
 
         // we've signed in, set all our existing podcasts to be non synced
-        DataManager.sharedManager.markAllPodcastsUnsynced()
+        if ServerSettings.lastSyncTime == nil {
+            DataManager.sharedManager.markAllPodcastsUnsynced()
```
Comment (leandroalonso) [inline podcasts/AuthenticationHelper.swift:71]: @geekygecko Before merging this I'd like to double-check with you as I might be missing any user case.

The app will only mark all podcasts as unsynced if the user has never logged in to any account in this device.

Comment (geekygecko) [reply podcasts/AuthenticationHelper.swift:71]: If they have just signed in, the last sync should be nil already. 🤔
If they signed out for six months and subscribed to many podcasts, then signed in again, won't that mean those new podcasts won't appear on their other devices?

**Review by SergioEstevao — APPROVED** [review]
Code looks good and tested the scenario described and all worked correctly. 

I do wonder why do we need to do step 4, Clear all folder information, the end user will not be able to do that, shouldn't this work correctly even without doing that?

File: podcasts/AuthenticationHelper.swift (hunk 1 above)
Comment (leandroalonso) [reply podcasts/AuthenticationHelper.swift:71]: > won't that mean those new podcasts won't appear on their other devices?

Based on my tests it syncs just fine (as per the PR description)

**Comment by leandroalonso** [comment]
> I do wonder why do we need to do step 4, Clear all folder information, the end user will not be able to do that, shouldn't this work correctly even without doing that?

Very good question, @SergioEstevao. I should have been more explicit in the PR description.

if you test these same steps in `trunk` (including using the "Clear all folder information"), your podcasts will be out of their folders when you sign back.

This is to simulate the issue that happened that is reported in  https://github.com/Automattic/pocket-casts-ios/issues/791#issuecomment-2125086525

A user won't be able to do that, but in the past, we had a bug that caused this scenario. A user with an old device with this "wrong data" can end up with their podcasts out of their folders, which is exactly what happened for this user.

**Comment by leandroalonso** [comment]
@SergioEstevao could you please review again? I added a feature flag so we can toggle this behavior in case it's needed.

**Review by SergioEstevao — APPROVED** [review]
All working great, and FF doing it's job!
