### PR TITLE
Fixes opening of shared link for episodes with the current position

### LINKED ISSUE #5: Share Links: links with position in them do not start from the shared position
### Steps to reproduce the behavior

1. Share a link with position from the app
2. Close the app and wipe the app's data
3. Open the link
4. Observe that the web player has the podcast loaded to the proper position
5. Tap the button to open the podcast in the app
6. Begin playing the podcast within the app and observe that it does not start playing from the proper position

### Additional information

IMG_5090 IMG_5091

What currently happens is that a screen pops up with some options and when you tap the play button the episode card opens but with the timestamp set either to zero or to the last point you were listening at if you had previously been listening to that episode.

IMG_5094 IMG_5095

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #5 

Open podcasts episodes at the correct position when user shares a link with the current position.

## To test

- Start the app 
- Get a shared link for Pocket Casts that share the episode and the current position. Example:`https://pca.st/s1h4dvtr?t=881.0`
- Open this link in Safari on the device/simulator
- Check that the app opens the podcast/episode and moves the current position to the time provided

One thing to keep in mind is that if you are currently listening to that episode the system will not move your current time.

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: podcasts/AppDelegate.swift [hunk 1]
```diff
@@ -177,6 +177,13 @@ class AppDelegate: UIResponder, UIApplicationDelegate {
                 return
             }
 
+            #if !os(watchOS)
+            if let timestamp {
```
Comment (leandroalonso) [inline podcasts/AppDelegate.swift:181]: This has the possibility of saving the episode and the `playedUpTo` even if the user doesn't hit play.

I don't think it's a big issue but we can solve it by sharing the `timestamp` with the episode screen and only saving `playedUpTo` if the user hits play.

You can do that by changing `NavigationManager.sharedManager.navigateTo(NavigationManager.episodePageKey, data: [NavigationManager.episodeUuidKey: episode.uuid])` to `NavigationManager.sharedManager.navigateTo(NavigationManager.episodePageKey, data: [NavigationManager.episodeUuidKey: episode.uuid, "timestamp": timestamp])`

Then on `EpisodeDetailViewController` you can handle that. As a plus, we remove the `DataManager` from here.

What do you think?

**Review by leandroalonso — CHANGES_REQUESTED** [review]
Left one suggestion, let me know what do you think!

File: podcasts/EpisodeDetailViewController+Actions.swift [hunk 2]
```diff
@@ -51,10 +51,16 @@ extension EpisodeDetailViewController {
             if !PlaybackManager.shared.playing() {
                 dismiss(animated: true, completion: nil)
             }
+            if let timestamp = timestamp {
```
Comment (SergioEstevao) [inline podcasts/EpisodeDetailViewController+Actions.swift:54]: Unsure if we should do this if this is the current playing episode. What do you think @leandroalonso ?

File: podcasts/AppDelegate.swift (hunk 1 above)
Comment (SergioEstevao) [reply podcasts/AppDelegate.swift:181]: @leandroalonso I update the code with the suggestion above, the code is a bit more complex because there is more changes to get the timestamp information to the episode detail view. What do you think?

File: podcasts/EpisodeDetailViewController+Actions.swift (hunk 2 above)
Comment (leandroalonso) [reply podcasts/EpisodeDetailViewController+Actions.swift:54]: Hmm good question! I'd put that into the edge case basket but it might be easy enough to check if it's the current playing episode?

**Review by leandroalonso — CHANGES_REQUESTED** [review]
@SergioEstevao I'm having an issue that is not directly related to your changes, but I think affects pretty much all the cases.

When I share a URL, ie.: https://pca.st/episode/b9e3b101-91b2-411b-8419-213a63079c03?t=528.0 and open it on the browser, it gets redirected to https://pca.st/kxp9rba1#t=528.0

With this format (the time being on `#t=<time>`, the app is unable to read the time and it's always missing. :(

Screenshot 2024-03-11 at 11 22 15

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/43">7.60</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by SergioEstevao** [comment]
@leandroalonso this PR is ready for another round of tests.

@geekygecko did some updates on the server side, so now the web page that is used for shared is sending the t has parameter.

For you to test this you will need to use the `staging` environment and I will recommend to do a clean install and create a new shared link in order to test this correctly.

**Review by leandroalonso — CHANGES_REQUESTED** [review]
@SergioEstevao this is still not working correctly for me. 🤔 

Check this video:

https://github.com/Automattic/pocket-casts-ios/assets/7040243/92737974-a015-4fcf-b887-ce51aa1fe110


Two things:

1. Sometimes displaying the episode screen fails, I can see that in the logs: `Attempt to present <UIAlertController: 0x108978c00> on <podcasts.EpisodeDetailViewController: 0x108b8b000> (from <podcasts.EpisodeDetailViewController: 0x108b8b000>) whose view is not in the window hierarchy.`
2. When it works, it seems the app is carrying the time correctly. But the moment I hit play it starts from the beginning.

**Comment by SergioEstevao** [comment]
@leandroalonso ready for another look

File: CHANGELOG.md [hunk 3]
```diff
@@ -4,6 +4,7 @@
 
 7.60
 -----
+- Opening a shared podcast episode link with the current position, now opens on the right position. [#5]
```
Comment (leandroalonso) [inline CHANGELOG.md]: This should be now on `7.61`.

**Review by leandroalonso — CHANGES_REQUESTED** [review]
@SergioEstevao I still can't get the episode to be played on the correct timestamp. 😬

Tested on Staging using this link: https://pcast.pocketcasts.net/lcg2ku96?t=2000

The app was freshly installed so there was no interaction with this episode:

https://github.com/Automattic/pocket-casts-ios/assets/7040243/794edcdf-eb9a-4758-8d8d-3d2b5416f799

**Comment by SergioEstevao** [comment]
@leandroalonso did one more change to ensure that the progress is not reset by the player. 
I now change the status of the episode to `in progress` so that the player does not reset it to zero, because it does that for all episodes with the `unplayed` or `played` status.

Do you mind to give it a look?

File: podcasts/EpisodeDetailViewController+Actions.swift [hunk 4]
```diff
@@ -51,10 +51,20 @@ extension EpisodeDetailViewController {
...
+                PlaybackManager.shared.seekTo(time: timestamp, startPlaybackAfterSeek: false)
+                updateProgress()
+            }
 
             PlaybackActionHelper.playPause()
         } else {
             dismiss(animated: true, completion: nil)
+            if let timestamp = timestamp {
+                DataManager.sharedManager.saveEpisode(playedUpTo: timestamp, episode: episode, updateSyncFlag: true)
+                DataManager.sharedManager.saveEpisode(playingStatus: .inProgress, episode: episode, updateSyncFlag: true)
```
Comment (leandroalonso) [inline podcasts/EpisodeDetailViewController+Actions.swift]: Can't we do

```suggestion
                episode.playingStatus = PlayingStatus.inProgress.rawValue
                episode.playedUpTo = timestamp
                DataManager.sharedManager.save(episode: episode)
```

This way we avoid doing two subsequent database calls changing the same episode.

Also, why do we need the `updateSyncFlag` to be `true`?

File: podcasts/EpisodeDetailViewController+Actions.swift [hunk 5]
```diff
@@ -51,10 +51,20 @@ extension EpisodeDetailViewController {
             if !PlaybackManager.shared.playing() {
                 dismiss(animated: true, completion: nil)
             }
+            if let timestamp = timestamp {
+                DataManager.sharedManager.saveEpisode(playedUpTo: timestamp, episode: episode, updateSyncFlag: true)
```
Comment (leandroalonso) [inline podcasts/EpisodeDetailViewController+Actions.swift]: Why do we need `updateSyncFlag` to be `true`? Can't we just let that be for the app to handle when the user is playing the episode?

**Review by leandroalonso — CHANGES_REQUESTED** [review]
@SergioEstevao tested and it's now working correctly!

I just left a few comments to reduce database calls and I have a question regarding the need to set `updateSyncFlag` to `true`, but maybe I'm missing something!

File: podcasts/EpisodeDetailViewController+Actions.swift (hunk 5 above)
Comment (SergioEstevao) [reply podcasts/EpisodeDetailViewController+Actions.swift]: I will follow your suggestion and test it again to see if all is good.

File: podcasts/EpisodeDetailViewController+Actions.swift (hunk 4 above)
Comment (SergioEstevao) [reply podcasts/EpisodeDetailViewController+Actions.swift]: I don't think we need it.

Comment (SergioEstevao) [reply podcasts/EpisodeDetailViewController+Actions.swift]: @leandroalonso I changed to false and all is working correctly, I also followed your other suggestion and all is ready for another round of review.

**Review by leandroalonso — APPROVED** [review]
Thanks for the patience and the changes @SergioEstevao. We're good to go!
