### PR TITLE
Transcripts fix crash on empty search

### LINKED ISSUE #1999: Transcripts Search crashes when pressing up and down on a empty result
### Description

Transcripts Search crashes when pressing up and down on a empty result

### Step-by-step reproduction instructions

1. Enable Transcripts FF
2. Start playing an episode with transcripts. Ex: any Cautionary Tales episode
3. Open the full screen player
4. Tap on transcripts icon
5. Tap on Search
6. Search for a word non-existing on the transcript
7. Tap on up or down
8. See crash

### Screenshots or screen recording

_No response_

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

iPad Mini iOS 17.5

### PR DESCRIPTION
**Pull request by SergioEstevao**
| 📘 Part of: #1848  
|:---:|

Fixes #1999 

I updated the code with a `guard` to prevent the crash detected when accessing empty search results, and I also added code to disable the up-down buttons when no search results are available.

## To test

1. Start the app
2. Ensure that you have the `transcripts` and `newShowNotesEndpoint` FF enabled
3. Start playing an episode with transcript supports. Ex:  One of this [list](https://lists.pocketcasts.com/b852a088-ccee-4e4b-a3c5-4bb7fd700a02)
4. Open the full screen player
5. Tap on transcripts icon
6. Tap on Search
7. Search for a word non-existing on the transcript
8. Check that the up-down buttons are disabled
9. Write now a word that exists in the transcript
10. See that the up-down buttons are enabled again

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: podcasts/TranscriptsViewController.swift [hunk 1]
```diff
@@ -541,6 +542,9 @@ extension TranscriptsViewController: TranscriptSearchAccessoryViewDelegate {
     }
 
     private func processMatch() {
+        guard !searchIndicesResult.isEmpty, currentSearchIndex >= 0, currentSearchIndex < searchIndicesResult.count else {
+            return
+        }
```
Comment (leandroalonso) [inline podcasts/TranscriptsViewController.swift]: I don't believe we need al those checks, we can do it like this:


```suggestion
        if searchIndicesResult.isEmpty {
            return
        }

```

Also not using a `guard` negation — we've been avoid doing those.

File: podcasts/TranscriptSearchAccessoryView.swift [hunk 2]
```diff
@@ -63,6 +63,11 @@ class TranscriptSearchAccessoryView: UIInputView {
         contentInsets: .init(top: 8, leading: 8, bottom: 8, trailing: 8)
     )
 
+    func enableUpDownButtons(_ enable: Bool) {
```
Comment (leandroalonso) [inline podcasts/TranscriptSearchAccessoryView.swift:66]: It was intentional to not do this because the search on other parts of iOS doesn't handle disabling the buttons.

I don't think it's bad having though.

However, when I first open the search the buttons are enabled, they should be disabled if we want this behavior to be correct.

**Review by leandroalonso — CHANGES_REQUESTED** [review]

File: podcasts/TranscriptSearchAccessoryView.swift (hunk 2 above)
Comment (SergioEstevao) [reply podcasts/TranscriptSearchAccessoryView.swift:66]: Updated here: [68a71f3](https://github.com/Automattic/pocket-casts-ios/pull/2000/commits/68a71f30977360d288e50254655404e124231845)

**Comment by leandroalonso** [comment]
@SergioEstevao since I renamed `TranscriptsViewController` to `TranscriptViewController` there's a merge issue here, I believe we should fix that before I do a final review

**Comment by SergioEstevao** [comment]
@leandroalonso done here: https://github.com/Automattic/pocket-casts-ios/pull/2000/commits/35c457d3a12f9895154d8d9f2b0e7df60276c8f2

**Comment by leandroalonso** [comment]
@SergioEstevao it looks like we have more merge conflicts due to my PR, sorry 😬

**Comment by pachlava** [comment]
While I was testing something else, on a different branch, I noticed that searching for emojis also results in crash. Not sure if it's the same crash as here, since technically emojis search is not an empty search.

**Comment by pachlava** [comment]
>Not sure if it's the same crash

Oh, I now realize it's the same kind of crash. Initially, I understood current crash as searching for empty string, whereas this meant navigating across empty search results. Never mind my comments here.

**Comment by SergioEstevao** [comment]
@leandroalonso conflicts sorted out.

**Review by leandroalonso — APPROVED** [review]
