### PR TITLE
Remove bookmark if it's a new bookmark and user pressed dismiss

### LINKED ISSUE #1510: Bookmarks: Still created when dismissing the prompt
### Description

If you are in the process of adding a bookmark but select the 'X' close button, the bookmark still gets created with a default name. 

Internal discussion: p1710339261635829-slack-C02A333D8LQ

### Step-by-step reproduction instructions

1. Listen to an episode
2. Attempt to create a bookmark
3. Close the popup without completing the flow, but notice it still creates a bookmark

### Screenshots or screen recording

_No response_

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

iPhone 13, iOS 17, Pocket Casts v7.58

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #1510 

Doesn't create a bookmark if you press dismiss (X) on a new bookmark

https://github.com/Automattic/pocket-casts-ios/assets/651601/836314b8-a6dd-4f3a-9f2a-3b86e6160835

## To test

- Start the app
- Play a podcast
- Open the player full screen
- Create a bookmark
- Tap on the X button on the top right on the new bookmark editor screen
- Check that no toast is shown and if you go to the player bookmarks screen no bookmark was created.

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/43">7.60</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: podcasts/Bookmarks/Player/BookmarksPlayerTabController.swift [hunk 1]
```diff
@@ -87,18 +87,25 @@ class BookmarksPlayerTabController: PlayerItemViewController {
...
+            self?.handleEditDismissed(bookmark: bookmark, isNew: isNew, title: title, cancel: cancel)
         })
 
         controller.source = viewModel.analyticsSource
 
         present(controller, animated: true)
     }
 
-    func handleEditDismissed(isNew: Bool, title: String) {
+    func handleEditDismissed(bookmark: Bookmark, isNew: Bool, title: String, cancel: Bool) {
```
Comment (leandroalonso) [inline podcasts/Bookmarks/Player/BookmarksPlayerTabController.swift]: nit: maybe `canceled` conveys a better meaning?

**Review by leandroalonso — APPROVED** [review]
✅ Tested the bookmark creation from player
✅ Tested canceling the bookmark creation from player
✅ Tested canceling editing on other places
