### PR TITLE
Up Next Emptying: Add device ID to up_next/sync call

### LINKED ISSUE #2961: [Task] Add device_id to up_next/sync API request
It's difficult to tell in our logs which device is sending an up next sync update. Adding the device ID should allow us to tell _which_ devices are sending incorrect `serverModified` information and which devices are clearing queues.

### PR DESCRIPTION
**Pull request by bjtitus**
| 📘 Part of: #2945 |
|:---:|

Fixes #2961

Adds the `deviceID` property to `up_next/sync` API requests.

## To test

* Start a proxy or set a breakpoint at `UpNextSyncTask:51` to see the device ID sent
* Make a change to your Up Next queue
* Verify that the device ID shows up in the `up_next/sync` request

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

File: scripts/update_proto.sh [hunk 1]
```diff
@@ -13,8 +13,12 @@ then
     exit 1
 fi
 
-brew upgrade protobuf
-brew upgrade swift-protobuf
+if command -v brew &> /dev/null; then
```
Comment (bjtitus) [inline scripts/update_proto.sh:16]: I don't use homebrew and this kept biting me, so I checked that homebrew exists before running these commands.

**Review by SergioEstevao — APPROVED** [review]
:shipit:
