### PR TITLE
Fix artwork aspect ratio in mini player

### LINKED ISSUE #1084: Wrong (resized) Artwork in MiniPlayer
Today I noticed that the artwork of a podcast was wrongly resized in the miniplayer. 

Original Artwork:
image

Artwork in MiniPlayer:
image

### PR DESCRIPTION
**Pull request by rviljoen**
Fixes #1084 

Landscape artwork is displayed as square in mini-player and not maintaining the correct aspect ratio. This fix uses the correct `contentMode` for the image

## To test
1. Find a podcast with landscape (rectangular) cover artwork (e.g. [this episode](https://pca.st/episode/70498efe-8055-44d1-b737-8ff4b71bb79b)) and press play to load landscape episode artwork
2. Close player to bring up mini-player
3. Note that the rectangular artwork is incorrectly rendered as a square
4. Retest with fix and note artwork rendered correctly

| Before | After |
|--------|--------|
| image | DAB91470-C60C-4C16-8488-9BED9DD0AF43_1_201_a |

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

File: podcasts/PodcastImageView.swift [hunk 1]
```diff
@@ -129,6 +129,7 @@ class PodcastImageView: UIView {
         if let imageView = imageView {
             imageView.backgroundColor = UIColor.clear
             imageView.clipsToBounds = true
+            imageView.contentMode = .scaleAspectFit
```
Comment (danielebogo) [inline podcasts/PodcastImageView.swift]: Hey @rviljoen after talking with our product team, we want to keep consistency with the other clients and keep the square format here. Would you mind change this into `scaleAspectFill`?
I can confirm that this change fixes this problem and it works with your previous fix in #3166

**Review by danielebogo — CHANGES_REQUESTED** [review]
Just left a small comment

File: podcasts/PodcastImageView.swift (hunk 1 above)
Comment (rviljoen) [reply podcasts/PodcastImageView.swift]: Code updated. Here are the results for some podcast referenced above:

image

Some of the text is now cut off, but I think this is OK as it not really noticeable on the small image on the mini-player

**Review by danielebogo — APPROVED** [review]
Thanks for the changes @rviljoen !
